version: "2"
services:
    client:
        build: ./client/
        image: webapp-client
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
            - /client/node_modules
        entrypoint: ["npm", "start"]
        links:
            - server
        networks:
            [webappnetwork]
    server:
        build: ./server/
        image: webapp-server
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - ./server:/server
            - /server/node_modules
        depends_on:
            - mongodb
        networks:
            [webappnetwork]
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth
        networks:
            - webappnetwork
    mongoseed:
        network_mode: host
        depends_on:
            - 'mongodb'
        environment:
            - DB_NAME=site-wide-warning-restful
            - REPLACE_ID=true
            - SET_TIMESTAMPS=true
            - DROP_DATABASE=true
        volumes:
            - './seed-data/:/seed-data/'
        working_dir: '/seed-data/data/'
        image: pkosiec/mongo-seeding
networks:
  webappnetwork:
      driver: bridge